# Generated by Django 4.2.7 on 2023-11-16 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_cadastro_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='senha',
        ),
        migrations.AddField(
            model_name='cadastro',
            name='historico',
            field=models.CharField(default='Valor Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='motivoadocao',
            field=models.CharField(default='Valor Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(default='Valor Padrão', max_length=50),
        ),
        migrations.AddField(
            model_name='cadastro',
            name='tipocasa',
            field=models.CharField(default='Valor Padrão', max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(default='Valor Padrão', max_length=75),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(default='Valor Padrão', max_length=50),
        ),
    ]
