# Generated by Django 4.2.7 on 2023-11-18 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_cadastro_senha_cadastro_historico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(max_length=100)),
                ('raca', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
    ]
