# Generated by Django 4.2.7 on 2023-11-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_animal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Animal',
            new_name='search',
        ),
    ]
