# Generated by Django 4.2.7 on 2023-11-18 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_animal_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=100)),
                ('idade', models.IntegerField()),
                ('raca', models.CharField(max_length=100)),
                ('historico_saude', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Ficha Animal',
                'verbose_name_plural': 'Fichas Animais',
            },
        ),
        migrations.CreateModel(
            name='Cuidador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
                ('responsável_por', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cuidador',
                'verbose_name_plural': 'Cuidadores',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_tutor', models.CharField(max_length=100)),
                ('data_adoção', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.animal')),
            ],
            options={
                'verbose_name': 'Historido de Adoção',
                'verbose_name_plural': 'Históricos de Adoção',
            },
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.animal')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Voluntário',
                'verbose_name_plural': 'Voluntários',
            },
        ),
        migrations.DeleteModel(
            name='search',
        ),
        migrations.AlterModelOptions(
            name='cadastro',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de adoção', 'verbose_name_plural': 'Formulários de adoção'},
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.EmailField(max_length=75),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='historico',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='motivoadocao',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='telefone',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='tipocasa',
            field=models.CharField(max_length=4),
        ),
    ]
