# Generated by Django 4.2.7 on 2023-11-19 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_animal_cuidador_historicoadocao_registro_voluntario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
