# Generated by Django 4.2.7 on 2023-11-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_animal_idade'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['nome'], 'verbose_name': 'Ficha Animal', 'verbose_name_plural': 'Fichas Animais'},
        ),
        migrations.AddField(
            model_name='animal',
            name='id_ficha',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
