# Generated by Django 4.2.7 on 2023-11-20 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_animal_foto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicoadocao',
            options={'verbose_name': 'Histórico de Adoção', 'verbose_name_plural': 'Históricos de Adoção'},
        ),
    ]
